
spring.application.name=piastria-wss
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

# not recommended because sends to the std output
# spring.jpa.show-sql=true

# show formatted sql
spring.jpa.properties.hibernate.format_sql=true

logging.file.name=${catalina.home}/logs/piastria.log
logging.level.com.romanpulov.piastriawss.aspect.ExecutionLoggingAspect=INFO

# Optional external file for sensitive Turso credentials.
spring.config.import=optional:file:./turso.properties
